# Rendements et valeur temporelle de l'argent

## Plan

- Introduction
- Rendements simples
- Rendements de portefeuille
- Annualisation
- Valeur temporelle de l'argent
- Rendements continus
- Exemples de comptabilité
- Points clés à retenir

## Introduction

Un rendement (ou *yield*) mesure un profit ou une perte sur un investissement. Les rendements sont généralement calculés en %.

**Questions :**

- Comment calculer un rendement entre deux observations ?
- Comment calculer une série de rendements sur une période ?
- Que signifient les rendements continus ?

**Définition utilisée ci-après :**

- Soit $P(t)$ une série temporelle de prix.
- $t$ désigne les pas de temps (équidistants) considérés : quotidien, hebdomadaire, mensuel, ...
- Exemple : $P(t) = \{100, 100.4, 102, 101.3, 102.8, \dots\}$

## Rendements simples

### Rendement simple sur une période

Le rendement simple sur une seule période, de $t-1$ à $t$, est

$$R_{1}(t) = \frac{P(t) - P(t - 1)}{P(t - 1)}$$

$$R_{1}(t) = \frac{P(t)}{P(t - 1)} -1$$

$$1 + R_{1}(t) = \frac{P(t)}{P(t - 1)}$$

**Exemples :**

1. $P(t - 1) = 50$, $P(t) = 60$, $R_{1}(t) = 60 / 50 - 1 = 20\%$
2. $P(t - 1) = 60$, $P(t) = 50$, $R_{1}(t) = 50 / 60 - 1 = -16.7\%$

Ce schéma présente des asymétries.

### Rendements simples - périodes multiples

Un rendement simple sur deux périodes, de $t-2$ à $t$, est

$$R_{2}(t) = \frac{P(t) - P(t - 2)}{P(t - 2)}$$

$$= \frac{P(t)}{P(t - 2)} -1$$

$$= \frac{P(t)}{P(t - 1)}\frac{P(t - 1)}{P(t - 2)} -1$$

$$1 + R_{2}(t) = (1 + R_{1}(t))(1 + R_{1}(t - 1))$$

On peut généraliser à $n$ périodes comme

$$1 + R_{n}(t) = \prod_{i = 0}^{n - 1}(1 + R_{1}(t - i))$$

→ On ne peut pas simplement additionner les rendements individuels.

### Exemple

Supposons l'évolution suivante des prix d'un titre donné :

| temps | prix |
|-------|------|
| 1     | 10   |
| 2     | 12   |
| 3     | 14   |
| 4     | 16   |

| période | rendement simple |
|---------|------------------|
| 1→2     | (12-10)/10 = 20% |
| 2→3     | (14-12)/12 = 16.7% |
| 3→4     | (16-14)/14 = 14.3% |

$$R_{4}(4) = (16 - 10) / 10 = 60\%$$

Somme : $20\% + 16.7\% + 14.3\% = 50.9\%$  
Produit : $(1 + 20\%)(1 + 16.7\%)(1 + 14.3\%) - 1 = 60\%$

Dans la suite, on ne distingue pas les périodes et on utilise $R(t)$.

## Rendements de portefeuille

- Un portefeuille est une collection de $n$ actifs avec des rendements $\mathbf{R}_i$.
- Chaque actif $i$ a une allocation $\alpha_i$ dans le portefeuille.
- On a $\sum_{i = 1}^{n} \alpha_i = 1$.
- En définissant le rendement du portefeuille comme $R_p = \sum_{i = 1}^{n} \alpha_i R_i$, on vérifie que

$$\left(\alpha_{1}(1 + R_{1}) + \alpha_{2}(1 + R_{2}) + \ldots +\alpha_{n}(1 + R_{n})\right) = \left(\sum_{i = 1}^{n}\alpha_{i} + \sum_{i = 1}^{n}\alpha_{i}R_{i}\right) = \left(1 + \sum_{i = 1}^{n}\alpha_{i}R_{i}\right) \equiv (1 + R_{p})$$

## Annualisation

- Permet de "comparer" des rendements sur différents horizons temporels.
- En définissant $R_a$ comme le rendement annuel, $R_m$ comme le rendement mensuel et $R_d$ comme le rendement quotidien, en utilisant la formule précédente, on peut écrire les transformations suivantes :

$$(1 + R_a) = (1 + R_m)^{12}$$

et

$$R_a = (1 + R_d)^{256} - 1$$

où l'on suppose 256 jours ouvrables dans une année (d'autres nombres sont utilisés : 250, 300, ...).

- Annualiser ne se fait donc pas en additionnant les rendements mensuels !

## Valeur temporelle de l'argent

### Partie 1

- CHF 1 aujourd'hui. Combien vaut-il demain ?
- Réponse : cela dépend du rendement et de la fréquence de paiement.

Soit $R$ le rendement à chaque période. Les valeurs futures (*future values*, FV) peuvent être calculées comme :

- $t=1 : PV \cdot (1+R) = FV_1$
- $t=2 : PV \cdot (1+R)^2 = FV_2$
- ...
- $t=n : PV \cdot (1+R)^n = FV_n$

→ $FV_n^{1} = PV \cdot (1+R)^n$ où $PV$ est la valeur présente.

Le paiement peut être plus fréquent, par exemple $m$ fois dans $n$ :

$$FV_n^{m} = PV \cdot (1 + R / m)^{m \cdot n}$$

Un paiement continu est défini comme $m \to \infty$ et on écrit

$$FV_n^{\infty} = \lim_{m\to \infty} PV \cdot (1 + R / m)^{m \cdot n} = PV \cdot \lim_{m\to \infty}(1 + R / m)^{m \cdot n} = PV e^{Rn}$$

### Partie 2

Supposons une valeur présente $PV = 1000$, $R = 10\%$ et $n = 1$ an.

| Fréquence      | Valeur future                     |
|----------------|-----------------------------------|
| Annuelle       | $1000 \cdot (1+0.1)^1 = 1100$     |
| Trimestrielle  | $1000 \cdot (1+0.1/4)^4 = 1103.8$ |
| Hebdomadaire   | $1000 \cdot (1+0.1/52)^{52} = 1105.1$ |
| Quotidienne    | $1000 \cdot (1+0.1/365)^{365} = 1105.2$ |
| Continue       | $1000 \cdot e^{0.1} = 1105.2$     |

- La capitalisation continue est pratique (utilisation d'exponentielles au lieu de fractions) mais peu réaliste, bien que largement utilisée dans les cadres théoriques.
- Une relation entre rendements continus et rendements simples :

$$PV \cdot (1 + R)^n = FV_n = PV e^{rn}$$

→ $\ln (1 + R) = r$ ce qui implique que $r < R$.

**Exemple :** $R = 10\%$, $r = \ln (1.1) = 9.53\%$ et $1000 \cdot e^{0.0953} = 1100$.

## Rendements continus

### Partie 1

Comment calcule-t-on un rendement sur une période si les intérêts sont continus ? On a :

$$r(t) = \ln (1 + R(t)) = \ln \left(\frac{P_t}{P_{t - 1}}\right)$$

→ $r(t) = \ln (P_t) - \ln (P_{t - 1})$

- Une différence de logarithmes.
- Les rendements continus sont symétriques.
- Il est plus facile de manipuler des logarithmes que des fractions en calcul.

Un rendement multi-périodes s'écrit pour un rendement sur deux périodes :

$$r_2(t) = \ln (1 + R_2(t)) = \ln \left(\frac{P_t}{P_{t - 2}}\right) = \ln \left(\frac{P_t}{P_{t - 1}} \cdot \frac{P_{t - 1}}{P_{t - 2}}\right)$$

$$r_2(t) = \ln \left(\frac{P_t}{P_{t - 1}}\right) + \ln \left(\frac{P_{t - 1}}{P_{t - 2}}\right) = r_1(t) + r_1(t - 1)$$

### Partie 2

Les rendements continus multi-périodes sont donc additifs et ne résultent plus de la composition des rendements de sous-périodes.

On peut généraliser à $n$ périodes comme

$$r_n(t) = \sum_{i = 0}^{n - 1} r_1(t - i)$$

Avec les mêmes hypothèses : $n$ actifs avec rendements $R_i$, chaque actif a une allocation $\alpha_i$ dans le portefeuille et $\sum_{i = 1}^{n} \alpha_i = 1$.

Le rendement continu d'un portefeuille devient

$$r_p = \ln \left(1 + R_p\right) = \ln \left(1 + \sum_{i = 1}^{n} \alpha_i R_i\right) \neq \sum_{i = 1}^{n} \alpha_i r_i$$

## Exemples de comptabilité

### Investisseur CHF investit dans un actif CHF

| Temps | Prix UBS_CHF | Position (actions) | Cash (CHF) | Valeur nette d'actif (NAV) (CHF) |
|-------|--------------|--------------------|------------|----------------------------------|
| 0     | 50           | 0                  | 1000       | 1000                             |
| 1     | 55           | 15                 | 175        | $15 \times 55 + 175 = 1000$      |
| 2     | 60           | 15                 | 175        | $15 \times 60 + 175 = 1075$      |
| 3     | 62           | 0                  | 1105       | 1105                             |

- Un exemple simple où un investisseur CHF achète 15 actions d'UBS.
- Une action est toujours cotée dans une devise, ici en CHF (UBS_CHF).
- L'investisseur achète au temps 1 et clôture la position au temps 3.
- Un P&L (*Profit and Loss*) de CHF 105 est observé.
- Un rendement de la NAV de $1105/1000 - 1 = 10.5\%$.
- Le prix UBS a augmenté de 55 à 62, soit $62/55 - 1 = 12.7\%$ et un rendement nul sur le cash est supposé.
- D'où $(1000-175)/1000 \times 12.7\% + 175/1000 \times 0\% = 10.5\%$.
- La performance est entièrement expliquée par l'évolution de l'action UBS.

### Investisseur CHF investit dans un actif USD (USDCHF statique, sans carry)

| Temps | AAPL_USD prix (USD) | Position (actions) | USD_CHF prix (CHF) | Position (USD) | Diff. intérêt (%) | Cash (CHF) | NAV (CHF) |
|-------|---------------------|--------------------|--------------------|----------------|-------------------|------------|-----------|
| 0     | 45                  | 0                  | 0.90               | 0              | 0%                | 1000.0     | 1000.0    |
| 1     | 48                  | 10                 | 0.90               | 568.0          | 0%                | 1000.0     | 1000.0    |
| 2     | 49                  | 10                 | 0.90               | 568.0          | 0%                | 1009.0     | 1009.0    |
| 3     | 48                  | 10                 | 0.90               | 568.0          | 0%                | 1000.0     | 1000.0    |
| 4     | 49                  | 0                  | 0.90               | 1009.0         | 0%                | 1009.0     | 1009.0    |

- Un exemple où un investisseur CHF achète 10 actions Apple à 1 et vend à 4.
- AAPL est coté en USD.
- NAV = position_AAPL × prix_AAPL × USDCHF + Cash.
- L'investisseur fait face à deux risques : action et devise (*Foreign Exchange*, FX).
- USD vs CHF ne change pas dans ce cas simple, ni de *carry*.
- P&L est CHF 9.0 et est entièrement expliqué par la performance de AAPL_USD.

### Investisseur CHF investit dans un actif USD (sans carry, avec variation du change)

| Temps | AAPL_USD prix (USD) | Position (actions) | USD_CHF prix (CHF) | Position (USD) | Diff. intérêt (%) | Cash (CHF) | NAV (CHF) |
|-------|---------------------|--------------------|--------------------|----------------|-------------------|------------|-----------|
| 0     | 45                  | 0                  | 0.89               | 0              | 0%                | 1000.0     | 1000.0    |
| 1     | 48                  | 10                 | 0.90               | 568.0          | 0%                | 1000.0     | 1000.0    |
| 2     | 49                  | 10                 | 0.90               | 568.0          | 0%                | 1009.0     | 1009.0    |
| 3     | 48                  | 10                 | 0.89               | 568.0          | 0%                | 995.2      | 995.2     |
| 4     | 49                  | 0                  | 0.88               | 999.2          | 0%                | 999.2      | 999.2     |

- Situation similaire au précédent.
- USD vs CHF change mais toujours pas de *carry*.
- P&L en 4 n'est pas ce qu'il était à $t = 2$ même si APPL_USD est revenu à 49.
- USD_CHF a baissé de $t = 2$ à $t = 4$.
- P&L est CHF -0.8 et s'explique par la performance de AAPL_USD (+) et USD_CHF (-).
- Peut-on annuler le risque de change ? Oui, en couvrant (*hedging*) mais cela a un coût.

### Investisseur CHF investit dans un actif USD (couvert, sans carry)

| Temps | AAPL_USD prix (USD) | Position (actions) | USD_CHF prix (CHF) | Position (USD) | Diff. intérêt (%) | Cash (CHF) | NAV (CHF) |
|-------|---------------------|--------------------|--------------------|----------------|-------------------|------------|-----------|
| 0     | 45                  | 0                  | 0.89               | 0              | 2%                | 1000       | 1000      |
| 1     | 48                  | 10                 | 0.90               | -480           | 2%                | 568.0      | 1000.0    |
| 2     | 49                  | 10                 | 0.90               | -490           | 2%                | 567.2      | 1008.2    |
| 3     | 48                  | 10                 | 0.89               | -480           | 2%                | 571.8      | 999.0     |
| 4     | 49                  | 0                  | 0.88               | 1007.6         | 2%                | 1007.6     | 1007.6    |

- Situation comme dans l'exemple précédent.
- Une couverture peut être ouverte et adaptée à la valorisation de la position principale.
- Les couvertures apportent des rendements.
- P&L est CHF 7.6 et s'explique par la performance de AAPL_USD et USD_CHF, et le coût de couverture (CHF 2.4).
- La NAV est moins volatile car un seul risque subsiste.

## Points clés à retenir

- Les rendements peuvent être simples, auquel cas ils se composent par un processus de multiplication.
- Les rendements peuvent être continus, auquel cas ils se composent par un processus de somme.
- La comptabilité dépend fortement de la devise de référence qui peut être couverte.

